seed = [114, 211, 149, 29, 162, 19, 137, 92, 158, 163, 71, 91, 19, 63, 98, 91, 224, 108, 230, 154, 7, 99, 93, 244, 235, 193, 72, 41, 127, 137, 95, 237]
seed_hash = [0x6f, 0x83, 0x63, 0xc6, 0x59, 0x1f, 0xa9, 0x4b, 0x2f, 0xf5, 0x05, 0x2b, 0xfc, 0x94, 0xb5, 0xff, 0xe2, 0x88, 0x18, 0x62, 0x12, 0x57, 0xcb, 0xc6, 0x06, 0x85, 0x68, 0xe7, 0x6b, 0xc8, 0x94, 0xf8]
